config/routes.rb
RailsApp::Application.routes.draw do

  resources :dogshares

  resources :people

  resources :dogs
 
  root 'dashboards#index'

  get '/register' => 'dashboards#register'

  

end

app/models/dog.rb
class Dog < ActiveRecord::Base
  belongs_to :owner, :class_name => "Person"
  has_many :sitters, :through => :dogshares, :class_name => "Person"
  has_many :dogshares

  has_attached_file :img, :styles => {:large => "500x500>", :medium => "300x300>", :thumb => "200x200>" }, :default_url => ":style/dogicon.jpg"

  # validates_attachment_presence :photo
  # validates_attachment_size :photo, :less_than => 5.megabytes
  # validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']


end

app/models/dogshare.rb
class Dogshare < ActiveRecord::Base
  belongs_to :dog 
  belongs_to :sitter, :class_name => "Person"
  belongs_to :owner, :class_name => "Person"
  
end

app/models/person.rb
class Person < ActiveRecord::Base

  has_many :owned_dogs, :foreign_key => "owner_id", :class_name => "Dogs"
  has_many :sat_dogs, :through => :dogshares, :class_name => "Dogs"
  has_many :dogshares, :foreign_key => "dogshare_id"

  has_attached_file :img, :styles => { :medium => "300x300>", :thumb => "200x200>" }, :default_url => ":style/dogpaw.png"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
 
  protect_from_forgery with: :exception


end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  
  def index
  end

  def register
  end
 
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: [:show, :edit, :update, :destroy]

  # GET /dogs
  # GET /dogs.json
  def index

    @dogs = Dog.all
    @dog = Dog.all.first

    @hash = Gmaps4rails.build_markers(@dogs) do |dog, marker|

    marker.lat 40.705353111111 #dog.latitude
    marker.lng -74.013745111111 #dog.longitude
    end

  end

  # GET /dogs/1
  # GET /dogs/1.json
  def show

  end

  # GET /dogs/new
  def new
    @dog = Dog.new
  end

  # GET /dogs/1/edit
  def edit
  end

  # POST /dogs
  # POST /dogs.json
  def create
    @dog = Dog.new(dog_params)

    respond_to do |format|
      if @dog.save
        format.html { redirect_to @dog, notice: 'Dog was successfully created.' }
        format.json { render action: 'show', status: :created, location: @dog }
      else
        format.html { render action: 'new' }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dogs/1
  # PATCH/PUT /dogs/1.json
  
  def update
    respond_to do |format|
      if @dog.update(dog_params)
        format.html { redirect_to @dog, notice: 'Dog was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dogs/1
  # DELETE /dogs/1.json
  def destroy
    @dog.destroy
    respond_to do |format|
      format.html { redirect_to dogs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dog
      @dog = Dog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dog_params
      params.require(:dog).permit(:img, :name, :age, :breed, :description, :temperament, :active, :housetrained, :picture, :special_needs, :available_start, :available_end, :owner_id, :dog_snippet)
    end
end

app/controllers/dogshares_controller.rb
class DogsharesController < ApplicationController
  before_action :set_dogshare, only: [:show, :edit, :update, :destroy]

  # GET /dogshares
  # GET /dogshares.json
  def index
    @dogshares = Dogshare.all
  end

  # GET /dogshares/1
  # GET /dogshares/1.json
  def show
  end

  # GET /dogshares/new
  def new
    @dogshare = Dogshare.new
  end

  # GET /dogshares/1/edit
  def edit
  end

  # POST /dogshares
  # POST /dogshares.json
  def create
    @dogshare = Dogshare.new(dogshare_params)

    respond_to do |format|
      if @dogshare.save
        format.html { redirect_to @dogshare, notice: 'Dogshare was successfully created.' }
        format.json { render action: 'show', status: :created, location: @dogshare }
      else
        format.html { render action: 'new' }
        format.json { render json: @dogshare.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dogshares/1
  # PATCH/PUT /dogshares/1.json
  def update
    respond_to do |format|
      if @dogshare.update(dogshare_params)
        format.html { redirect_to @dogshare, notice: 'Dogshare was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @dogshare.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dogshares/1
  # DELETE /dogshares/1.json
  def destroy
    @dogshare.destroy
    respond_to do |format|
      format.html { redirect_to dogshares_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dogshare
      @dogshare = Dogshare.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dogshare_params
      params.require(:dogshare).permit(:dog_id, :sitter_id, :available_day_start, :available_day_end)
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render action: 'show', status: :created, location: @person }
      else
        format.html { render action: 'new' }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:img, :name, :zip, :dog_owner, :bio, :picture, :available_start, :available_end, :needs_dogsitting)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/dogshares_helper.rb
module DogsharesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/dashboards/index.html.erb
    <title>dogg.io</title>
    

    <!-- Bootstrap core CSS -->
    <link href="../assets/stylesheets/bootstrap.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="carousel.css" rel="stylesheet">
    
    <!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
        <li data-target="#myCarousel" data-slide-to="4"></li>
      </ol>

      <!-- images/text in carousel
      ================================================ -->

      <div class="carousel-inner">
        <div class="item active">
          <%= image_tag 'share.jpg', :class => 'home-img', :alt => "First Slide" %>
          <div class="container">
            <div class="carousel-caption">
              <h1>walk a dog</h1>
              <p>Stay engaged in your community with people and furry animals alike by walking a neighborhood dog.</p>
              <p><a class="btn btn-lg btn-primary" href="/dogs" role="button">find a dog</a></p>
              <p><a class="btn btn-lg btn-primary" href="/people" role="button">find a doglover</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <%= image_tag "schweenrocky.jpg", :class => "home-img", :alt => "Second Slide" %>
          <div class="container">
            <div class="carousel-caption">
              <h1>make a friend</h1>
              <p>More interaction, less isolation. Pets and humans alike can benefit from a little companionship.</p>
              <p><a class="btn btn-lg btn-primary" href="/dogs" role="button">find a dog</a></p>
              <p><a class="btn btn-lg btn-primary" href="/people" role="button">find a doglover</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <%= image_tag 'pillows.jpg', :class => "home-img", :alt => "Third Slide" %>
          <div class="container">
            <div class="carousel-caption">
              <h1>canines in your community</h1>
              <p>You love dogs and cannot have one -or- your heart aches imagining your dog bored during the days? Become a part of the dogg.io movement by walking or sharing a dog.</p>
              <p><a class="btn btn-lg btn-primary" href="/dogs" role="button">find a dog</a></p>
              <p><a class="btn btn-lg btn-primary" href="/people" role="button">find a doglover</a></p>
            </div>
          </div>
        </div>
         <div class="item">
          <%= image_tag 'IMG_3168.jpg', :class => "home-img", :alt => "Fourth Slide" %>
          <div class="container">
            <div class="carousel-caption">
              <h1>go for a run</h1>
              <p>"A tired dog is a happy dog." Go for a daily 30-minute walk or run with a dog. It will keep you (and your canine buddy) healthy and energized. </p>
              <p><a class="btn btn-lg btn-primary" href="/dogs" role="button">find a dog</a></p>
              <p><a class="btn btn-lg btn-primary" href="/people" role="button">find a doglover</a></p>
            </div>
          </div>
        </div>
         <div class="item">
          <%= image_tag 'IMG_3999.jpg', :class => "home-img", :alt => "Fifth Slide" %>
          <div class="container">
            <div class="carousel-caption">
              <h1>give back</h1>
              <p>Share the responsibility of caring for an animal in your community by helping out dogs in your zip code.</p>
              <p><a class="btn btn-lg btn-primary" href="/dogs" role="button">find a dog</a></p>
              <p><a class="btn btn-lg btn-primary" href="/people" role="button">find a doglover</a></p>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
      <a class="right carousel-control" href="#myCarousel" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
    </div>
    
    <!-- /.carousel -->

    <div id="map-canvas"></div>
 


   

app/views/dashboards/register.html.erb
<!-- Bootstrap core CSS -->
    <link href="../assets/stylesheets/bootstrap.css" rel="stylesheet">

<!-- Custom styles for this template -->
    <link href="register.css" rel="stylesheet">

  <div class="p-1">
    <div class="paragraph-caption">
      <h2>Dogs and Owners</h2>
      There's no reason our dogs can't have more than their 'best friend'.<p>
      Register your pup to honor their free time by giving the gift of a new playmate when you're not around.<br>
      <p><a class="btn btn-lg btn-primary paragraph-btn" href="/dogs/new" role="button">Register your Dog</a></p>
    </div>  

    <div class="paragraph-caption">
      <h2>Doglovers</h2>
      Sign up as a Doglover to hang out with cool dogs in your neighborhood!<p>
      You can browse the fun assortment of dogs around you to hang out with in case you don't have your own.<br>
      <p><a class="btn btn-lg btn-primary paragraph-btn" href="/people/new" role="button">Register as Doglover</a></p>
      </div>
    </div>

    <img src="assets/turtle.jpg" class="feature-img center-block">
    
  </div>

app/views/dogs/_form.html.erb
<%= form_for(@dog) do |f| %>
  <% if @dog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dog.errors.count, "error") %> prohibited this dog from being saved:</h2>
      <ul>
      <% @dog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Upload_an_image %><br>
    <%= f.file_field :img %>
  </div>
  
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :owner %><br>
    <%= f.select(:owner_id, options_for_select(Person.all.map { |o| [o.name, o.id ]})) %>
  </div>
  
  <div class="field">
    <%= f.label :dog_snippet %><br>
    <%= f.text_field :dog_snippet %>
  </div>

  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>

  <div class="field">
    <%= f.label :breed %><br>
    <%= f.text_field :breed %>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :temperament %><br>
    <%= f.text_field :temperament %>
  </div>

  <div class="field">
    <%= f.label :active %><br>
    <%= f.text_field :active %>
  </div>

  <div class="field">
    <%= f.label :housetrained %><br>
    <%= f.check_box :housetrained %>
  </div>

  <div class="field">
    <%= f.label :special_needs %><br>
    <%= f.text_area :special_needs %>
  </div>

  <div class="input-prepend date" data-date=" " data-date-format="mm/dd/yyyy">
    <%= f.label :available_start %><br>
    <input class="col-md-2" id="dp3" size="16" type="text" name="dog[available_start]">
    <span class="add-on"><i class="icon-th"></i></span>
  </div>
  <br>

  <div class="input-append date" data-date=" " data-date-format="mm/dd/yyyy">
    <%= f.label :available_end %><br>
    <input class="col-md-2" id="dp4" size="16" type="text" name="dog[available_end]">
    <span class="add-on"><i class="icon-th"></i></span>
  </div><br>

  <div class="actions">
    <%= f.submit 'Create Dog', class: "btn btn-lg btn-primary paragraph-btn" %>
  </div>

<% end %>

app/views/dogs/edit.html.erb
<h1>Editing <%= @dog.name %></h1>

<%= render 'form' %>

<%= link_to 'Show', @dog %> |
<%= link_to 'Back', dogs_path %>

app/views/dogs/index.html.erb
<link href="../assets/stylesheets/bootstrap.css" rel="stylesheet">

<div id="map" data-owner-locations='<%=raw @hash.to_json %>'>
</div>
<br>
<div id="map-toggle" class="header_1"><a class="btn btn-lg btn-primary">Meet the dogs in your neighborhood.</a></div>


<div class="container marketing">
  <br>
  <br>
  <br>
  <% count = 0 %>
  <% @dogs.each_slice(3) do |slice| %>
    <div class="row">
      <% slice.each do |dog| %>
        <div class="col-lg-4 dog">
          <%= image_tag(dog.img.url(:thumb), :class => "img-circle") %>
          <h2><%= dog.name %></h2>
          <p><b>Owner:</b> <%= dog.owner.name %></p>
          <p><em><%= dog.dog_snippet %></em></p>
          <p><a class="btn btn-default" href="<%= dog_path(dog) %>" role="button">View details &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
      <% end %>
  </div><!-- /.row -->
  <% end %>
</div>

app/views/dogs/new.html.erb
<!-- <div class="centered"> -->
  <h1>Add a new dog</h1>

  <%= render 'form' %>

  <%= link_to 'Back', dogs_path %>
<!-- </div> -->

app/views/dogs/show.html.erb
<p id="notice"><%= notice %></p>

<div class="center">
  <%= image_tag(@dog.img.url(:medium), :class => "img-circle") %>
  <h2><%= @dog.name %></h2>
  <p><em><%= @dog.dog_snippet %></em></p>
</div>


<div class="col-sm-6 dog-p-left">
  <p>

    <strong>Description:</strong>
    <%= @dog.description %>
  </p>

  <p>
    <strong>Temperament:</strong>
    <%= @dog.temperament %>
  </p>

  <p>
    <strong>Active:</strong>
    <%= @dog.active %>
  </p>

  <p>
    <strong>Special needs:</strong>
    <%= @dog.special_needs %>
  </p>
</div>

<div class="col-lg-6 center dog-p-right">

  <% if false %>
  <%= image_tag(@dog.owner.img.url(:thumb), :class => "img-circle") %>
  <% end %>
  <div class="owner-box">
    <p>
      <strong>Owner:</strong>
        <%= link_to @dog.owner.name, person_path(@dog.owner.id) %>
    </p>
    <p>
      <strong>Zip:</strong>
        <%= @dog.owner.zip %>
    </p>
    <p>
    </div>
  <strong>Age:</strong>
  <%= @dog.age %>
  </p>
  <p>
    <strong>Breed:</strong>
    <%= @dog.breed %>
  </p>
  <p>
  <strong>Housetrained:</strong>
  <%= if @dog.housetrained == true 
    "yes"
    else "no"
    end %>
  </p>

  <p>
    <strong>Available from:</strong>
    <%= @dog.available_start %><br>
  <p>
    <strong>Available to:</strong>
    <%= @dog.available_end %>
  </p>
</div>


  <div class="edit-btn">
    <p><%= link_to 'Back to Dogs', dogs_path %></p>
    <%= link_to 'Edit', edit_dog_path(@dog), class: "btn btn-lg btn-primary dog-btn" %>
  </div>



  

app/views/dogshares/_form.html.erb
<%= form_for(@dogshare) do |f| %>
  <% if @dogshare.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dogshare.errors.count, "error") %> prohibited this dogshare from being saved:</h2>

      <ul>
      <% @dogshare.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :dog_id %><br>
    <%= f.number_field :dog_id %>
  </div>
  

  <div class="input-prepend date" data-date=" " data-date-format="dd-mm-yyyy">
    <%= f.label :available_start %><br>
    <input class="col-md-2" id="dp3" size="16" type="text" value=" " name="dogshare[available_day_start]">
    <span class="add-on"><i class="icon-th"></i></span>
  </div>
  <br>

  <div class="input-append date" data-date=" " data-date-format="dd-mm-yyyy">
    <%= f.label :available_end %><br>
    <input class="col-md-2" id="dp4" size="16" type="text" value=" " name="dogshare[available_day_end]">
    <span class="add-on"><i class="icon-th"></i></span>
  </div>
<br>
<br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dogshares/edit.html.erb
<h1>Editing dogshare</h1>

<%= render 'form' %>

<%= link_to 'Show', @dogshare %> |
<%= link_to 'Back', dogshares_path %>

app/views/dogshares/index.html.erb
<h1>Listing dogshares</h1>

<table>
  <thead>
    <tr>
      <th>Dog</th>
      <th>Sitter</th>
      <th>Available</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @dogshares.each do |dogshare| %>
      <tr>
        <td><%= dogshare.dog_id %></td>
        <td><%= dogshare.sitter_id %></td>
        <td><%= link_to 'Show', dogshare %></td>
        <td><%= link_to 'Edit', edit_dogshare_path(dogshare) %></td>
        <td><%= link_to 'Destroy', dogshare, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dogshare', new_dogshare_path %>

app/views/dogshares/new.html.erb
<h1>New dogshare</h1>

<%= render 'form' %>

<%= link_to 'Back', dogshares_path %>

app/views/dogshares/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Dog:</strong>
  <%= @dogshare.dog_id %>
</p>

<p>
  <strong>Sitter:</strong>
  <%= @dogshare.sitter_id %>
</p>

<p>
  <strong>Available from:</strong>  
  <%= @dogshare.available_day_start %><br>
  <strong>Available to:</strong>
  <%= @dogshare.available_day_end %>
</p>

<%= link_to 'Edit', edit_dogshare_path(@dogshare) %> |
<%= link_to 'Back', dogshares_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>dogg.io</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <style>
      html, body, #map-canvas {
        height: 100%;
        margin: 0px;
        padding: 0px
      }
    </style>

    <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

</head>
  <!-- NAVBAR
================================================== -->
  <body>
    <div class="navbar-wrapper">
      <div class="container">

        <div class="navbar navbar-inverse navbar-static-top" role="navigation">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="/">dogg.io</a>
            </div>
            <div class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li><a href="/dogs">Dogs</a></li>
                <li><a href="/people">Friends</a></li>
               <!--  <li><a href="#about">About</a></li>
                <li><a href="#contact">Contact</a></li> -->
              </ul>
              <ul class="nav navbar-nav navbar-right">
                <li><a href="/register">Register</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
</head>
<body>
   
  <div class="container">
  <div class="page">
  </div>

<%= yield %>

  </div>

</body>

</html>

app/views/people/_form.html.erb
  <%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>
      <ul>
      <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Upload_an_image %><br>
    <%= f.file_field :img %>
  </div>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :zip %><br>
    <%= f.number_field :zip %>
  </div>

   <div class="field">
    <%= f.label :bio %><br>
    <%= f.text_field :bio %>
  </div>


  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>

  <! -- datetime picker -->
 
  <div class="input-prepend date" data-date=" " data-date-format="dd-mm-yyyy">
    <%= f.label :available_start %><br>
    <input class="col-md-2" id="dp1" size="16" type="text" value=" " name="person[available_start]">
    <span class="add-on"><i class="icon-th"></i></span>
  </div>
  <br>

  <div class="input-append date" data-date=" " data-date-format="dd-mm-yyyy">
    <%= f.label :available_end %><br>
    <input class="col-md-2" id="dp2" size="16" type="text" value=" " name="person[available_end]">
    <span class="add-on"><i class="icon-th"></i></span>
  </div>
<br>
<br>
 <div class="actions">
    <%= f.submit 'Register Person', class: "btn btn-lg btn-primary paragraph-btn" %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing <%= @person.name %></h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back to Doglovers', people_path %>

app/views/people/index.html.erb
<link href="../assets/stylesheets/bootstrap.css" rel="stylesheet">

<div id="map" data-owner-locations='<%=raw @hash.to_json %>'>
</div>
<br>
<div id="map-toggle" class="header_1"><a class="btn btn-lg btn-primary">Introduce your dog to new people friends nearby.</a></div>

<div class="container marketing">
  <br>
  <br>
  <br>
  <% count = 0 %>
  <% @people.each_slice(3) do |slice| %>
    <div class="row">
      <% slice.each do |person| %>
        <div class="col-lg-4 dog">
          <%= image_tag(person.img.url(:thumb), :class => "img-circle") %>
          <h2><%= person.name %></h2>
          <p><%= person.person_snippet %></p>
          <p><a class="btn btn-default" href="<%= person_path(person) %>" role="button">View details &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
      <% end %>
  </div><!-- /.row -->
  <% end %>
</div>

app/views/people/new.html.erb
<h1>New person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<div class="row">
  <div class="col-md-3">
  </div>

<div class="col-md-6 centered">

<p id="notice"><%= notice %></p>

<p>
  <%= image_tag(@person.img.url(:medium), :class => "img-circle") %>
</p>
  
<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @person.zip %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @person.bio %>
</p>

<!-- <p>
  <strong>Dogs:</strong>
  <#%= @person.dog.name %>
</p> -->

<p>
  <strong>Available from:</strong>  
  <%= @person.available_start %><br>
  <strong>Available to:</strong>
  <%= @person.available_end %>
</p>

<strong><a href="mailto:<%= @person.email %>">Contact <%= @person.name %></a> 
</strong> 
<br>

<div class="dog-p-right">
<%= link_to 'Back to Doglovers', people_path %>
</div>
    <%= link_to 'Edit', edit_person_path(@person), class: "btn btn-lg btn-primary dog-btn" %>